baseURL = "https://samyev.netlify.app/"
languageCode = "pt-br"
title = "Meu blog"
theme = "github-style"

[params]
  author = "samyev"
  description = "Meu blog"
  avatar = "https://samyev.netlify.app/images/avatar.jpg"	
  

